FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# MANDIRI_TEST

Technical Assessment for Solution Analyst

## Login [/user/login]

### Login [POST]

isUsingBiometric:
true jika login dengan biometric, false jika tidak

type :
FACE
FINGERPRINT

cid:
id customer

+ Request (application/json)

        {
            "username":"dsqdkjsqndkqufqifq",
            "password":"sdajdqwuqddsqdqfasd",
            "biometric":{
                "type":"FINGERPRINT",
                "value":"dsadadnqkwbqfkfjqdsqmdsknqkqd"
            },
            "deviceInfo":{
                "deviceId":"dw1rwr1r17rdw11rfw1",
                "deviceType":"Android",
                "deviceModel":"Xiomi Redmi note 11 Pro",
                "deviceOs":"12",
                "isRooted":false
            },
            "isUsingBiometric":true
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {
                "cid": "123123123123",
                "fullname":"Alexander Grahambel",
                "email": "alex@gmail.com",
                "phoneNumber": "081208120812",
                "type": "RETAIL",
                "isVerified": true,
                "kreditScore":"A",
                "sessionId":"21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir",
                "lastLogin": "2022-06-13 22:20:50"
            }
        }



## Register [/user/register]

### Register [POST]

type :
FACE
FINGERPRINT

cid:
id customer

+ Request (application/json)

        {
            "fullname":"Alexandre Grahambel",
            "email":"alex@gmail.com",
            "phoneNumber":"081208120812",
            "username":"alex.grahambel",
            "password":"sdajdqwuqddsqdqfasd",
            "biometricFace":"dsadadnqkwbqfkfjqdsqmdsknqkqd",
            "biometricFingerprint":"dsadadnqkwbqfkfjqdsqmdsknqkqd",
            "deviceInfo":{
                "deviceId":"dw1rwr1r17rdw11rfw1",
                "deviceType":"Android",
                "deviceModel":"Xiomi Redmi note 11 Pro",
                "deviceOs":"12",
                "isRooted":false
            },
            "isUsingBiometric":true
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {
                "cid": "123123123123",
                "fullname":"Alexander Grahambel",
                "email": "alex@gmail.com",
                "phoneNumber": "081208120812",
                "type": "RETAIL",
                "isVerified": true,
                "kreditScore":"A",
                "sessionId":"21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir",
                "lastLogin": "2022-06-13 22:20:50"
            }
        }



## Register Detail [/user/register-detail]

### Register Detail [POST]


+ Request (application/json)

        {
            "birthOfDate":"20000120",
            "lastEducation":"S1",
            "maritalStatus":"Single",
            "workType":"Karyawan Swasta",
            "businessName":"PT BANK MANDIRI",
            "businessIndustry":"Finance",
            "position":"Staff",
            "sourceOfFunds":"Gaji",
            "monthlyIncome":"10000000",
            "monthlySpending":"4500000",
            "workSinceMonth":"03",
            "workSinceYear":"2022"
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }
        
        
        
## Register Document [/user/register-document]

### Register Document [POST]


+ Request (application/json)

        {
            "document":"
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }