FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# MANDIRI_TEST

Technical Assessment for Solution Analyst

## Login [/user/login]

### Login [POST]

isUsingBiometric:
true jika login dengan biometric, false jika tidak

type :
FACE
FINGERPRINT

cid:
id customer

+ Request (application/json)

        {
            "username":"dsqdkjsqndkqufqifq",
            "password":"sdajdqwuqddsqdqfasd",
            "deviceInfo":{
                "deviceId":"dw1rwr1r17rdw11rfw1",
                "deviceType":"Android",
                "deviceModel":"Xiomi Redmi note 11 Pro",
                "deviceOs":"12",
                "isRooted":false
            },
            "isUsingBiometric":true
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {
                "cid": "123123123123",
                "fullname":"Alexander Grahambel",
                "email": "alex@gmail.com",
                "phoneNumber": "081208120812",
                "type": "RETAIL",
                "isVerified": true,
                "kreditScore":"A",
                "sessionId":"21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir",
                "lastLogin": "2022-06-13 22:20:50"
            }
        }



## Register [/user/register]

### Register [POST]

type :
FACE
FINGERPRINT

cid:
id customer

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir
    

+ Request (application/json)

        {
            "fullname":"Alexandre Grahambel",
            "email":"alex@gmail.com",
            "phoneNumber":"081208120812",
            "username":"alex.grahambel",
            "password":"sdajdqwuqddsqdqfasd",
            "biometricFace":"dsadadnqkwbqfkfjqdsqmdsknqkqd",
            "biometricFingerprint":"dsadadnqkwbqfkfjqdsqmdsknqkqd",
            "deviceInfo":{
                "deviceId":"dw1rwr1r17rdw11rfw1",
                "deviceType":"Android",
                "deviceModel":"Xiomi Redmi note 11 Pro",
                "deviceOs":"12",
                "isRooted":false
            },
            "isUsingBiometric":true
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {
                "cid": "123123123123",
                "fullname":"Alexander Grahambel",
                "email": "alex@gmail.com",
                "phoneNumber": "081208120812",
                "type": "RETAIL",
                "isVerified": true,
                "kreditScore":"A",
                "sessionId":"21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir",
                "lastLogin": "2022-06-13 22:20:50"
            }
        }



## Register Detail [/user/register-detail]

### Register Detail [POST]


Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

+ Request (application/json)

        {
            "dateOfBirth":"20000120",
            "lastEducation":"S1",
            "maritalStatus":"Single",
            "workType":"Karyawan Swasta",
            "businessName":"PT BANK MANDIRI",
            "businessIndustry":"Finance",
            "position":"Staff",
            "sourceOfFunds":"Gaji",
            "monthlyIncome":10000000,
            "monthlySpending":4500000,
            "workSinceMonth":"03",
            "workSinceYear":"2022"
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }
        
        
        
## Register Document [/user/register-document]

### Register Document [POST]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

id empty if edit document, not empty if add document

file is url path document

+ Request (application/json)

        {
            "document":[
                {
                    "id":"13132456da5d46a56",
                    "type":"KTP",
                    "number":"12012012012012012",
                    "file":"http://image.bankmandiri.com"
                },
                {
                    "id":"",
                    "type":"NPWP",
                    "number":"1445654985462",
                    "file":"http://image.bankmandiri.com"
                }
            ]
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }
        
        

## Register Emergency Contact [/user/register-emergency-contact]

### Register Emergency Contact [POST]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

id empty if edit contact, not empty if add contact

+ Request (application/json)

        {
            "id":"",
            "fullname":"Desi Ratnasari",
            "phoneNumber":"081308130813",
            "email":"desi@gmail.com",
            "relationshipStatus":"Saudara Kandung"
        }
        
+ Response 200 (application/json)

        {
            "code":"00000",
            "title":"Sukses",
            "message":"Sukses",
            "data":{}
        }

    
## Register Emergency Contact Address [/user/register-emergency-address]

### Register Emergency Contact Address [POST]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

id empty if edit address, not empty if add address

addressType :
Domisili
Ktp
Kerja
Emergency

+ Request (application/json)

        {
            "address":[
                {
                    "id":"3212345632123",
                    "idEmergency":"1231546213456",
                    "addressType":"Emergency",
                    "address":"Jalan jalan",
                    "rt":"001",
                    "rw":"002",
                    "village":"Cibogo",
                    "district":"Cisauk",
                    "regency":"Tangerang",
                    "provinci":"Banten",
                    "postalCode":"15021",
                    "telephone":"02123154"
                }
            ]
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }
        
        
        
## Register Address [/user/register-address]

### Register Address [POST]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

id empty if edit address, not empty if add address

addressType :
Domisili
Ktp
Kerja
Emergency

+ Request (application/json)

        {
            "address":[
                {
                    "id":"3212345632123",
                    "addressType":"Domisili",
                    "address":"Jalan jalan",
                    "rt":"001",
                    "rw":"002",
                    "village":"Cibogo",
                    "district":"Cisauk",
                    "regency":"Tangerang",
                    "provinci":"Banten",
                    "postalCode":"15021",
                    "telephone":"02123154"
                },
                {
                    "id":"3212345632123",
                    "addressType":"Ktp",
                    "address":"Jalan jalan",
                    "rt":"001",
                    "rw":"002",
                    "village":"Cibogo",
                    "district":"Cisauk",
                    "regency":"Tangerang",
                    "provinci":"Banten",
                    "postalCode":"15021",
                    "telephone":"02123154"
                }
            ]
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }
        
        
## Register Bank Account [/user/register-bank-account]

### Register Bank Account [POST]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

id empty if edit bank account, not empty if add bank account

+ Request (application/json)

        {
            "bankAccount":[
                {
                    "id":"3212345632123",
                    "bankName":"Bank Mandiri",
                    "bankNumber":"123456875",
                    "bankAccountName":"Alexander Grahambel"
                }
            ]
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }
        
        
## Get User Profile [/user/profile]

### Get User Profile [GET]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

id empty if edit bank account, not empty if add bank account


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {
                "userDetail":{
                    "dateOfBirth":"20000120",
                    "lastEducation":"S1",
                    "maritalStatus":"Single",
                    "workType":"Karyawan Swasta",
                    "businessName":"PT BANK MANDIRI",
                    "businessIndustry":"Finance",
                    "position":"Staff",
                    "sourceOfFunds":"Gaji",
                    "monthlyIncome":10000000,
                    "monthlySpending":4500000,
                    "workSinceMonth":"03",
                    "workSinceYear":"2022"
                },
                "document":[
                    {
                        "id":"13132456da5d46a56",
                        "type":"KTP",
                        "number":"12012012012012012",
                        "file":"http://image.bankmandiri.com"
                    },
                    {
                        "id":"",
                        "type":"NPWP",
                        "number":"1445654985462",
                        "file":"http://image.bankmandiri.com"
                    }
                ],
                "emergencyContact":[
                    {
                        "id":"",
                        "fullname":"Desi Ratnasari",
                        "phoneNumber":"081308130813",
                        "email":"desi@gmail.com",
                        "relationshipStatus":"Saudara Kandung"
                    }
                ],
                "address":[
                    {
                        "id":"3212345632123",
                        "idEmergency":"",
                        "addressType":"Domisili",
                        "address":"Jalan jalan",
                        "rt":"001",
                        "rw":"002",
                        "village":"Cibogo",
                        "district":"Cisauk",
                        "regency":"Tangerang",
                        "provinci":"Banten",
                        "postalCode":"15021",
                        "telephone":"02123154"
                    },
                    {
                        "id":"3212345632123",
                        "idEmergency":"",
                        "addressType":"Ktp",
                        "address":"Jalan jalan",
                        "rt":"001",
                        "rw":"002",
                        "village":"Cibogo",
                        "district":"Cisauk",
                        "regency":"Tangerang",
                        "provinci":"Banten",
                        "postalCode":"15021",
                        "telephone":"02123154"
                    },
                    {
                        "id":"3212345632123",
                        "idEmergency":"1231546213456",
                        "addressType":"Emergency",
                        "address":"Jalan jalan",
                        "rt":"001",
                        "rw":"002",
                        "village":"Cibogo",
                        "district":"Cisauk",
                        "regency":"Tangerang",
                        "provinci":"Banten",
                        "postalCode":"15021",
                        "telephone":"02123154"
                    }
                ],
                "bankAccount":[
                    {
                        "id":"3212345632123",
                        "bankName":"Bank Mandiri",
                        "bankNumber":"123456875",
                        "bankAccountName":"Alexander Grahambel"
                    }
                ]
            }
        }



## Get Loan Variable [/user/loan-variable]

### Get Loan Variable [GET]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {
                "loanVariable":[
                    {
                        "kreditLimit":10000000,
                        "tenor":12,
                        "flatRate":1.69,
                        "effectiveRate":2.95,
                        "provision":600000,
                        "disbursementFee":120000,
                        "insuranceFee":0,
                        "installment":1000000,
                        "lateInterest":6,
                        "lateFee":200000,
                        "lateTenor":1,
                        "lateTenorUnit":"Month",
                    },
                    {
                        "kreditLimit":10000000,
                        "tenor":6,
                        "flatRate":1.69,
                        "effectiveRate":2.95,
                        "provision":600000,
                        "disbursementFee":120000,
                        "insuranceFee":0,
                        "installment":1000000,
                        "lateInterest":6,
                        "lateFee":200000,
                        "lateTenor":1,
                        "lateTenorUnit":"Month",
                    }
                ]
            }
        }


## Loan Request [/user/loan-request]

### Loan Request [POST]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

+ Request (application/json)

        {
            "kreditLimit":10000000,
            "purpose":"Pendidikan",
            "tenor":12,
            "flatRate":1.69,
            "effectiveRate":2.95,
            "provision":600000,
            "disbursementFee":120000,
            "insuranceFee":0,
            "lateInterest":6,
            "lateFee":200000,
            "lateTenor":1,
            "lateTenorUnit":"Month",
            "receiveFunds":9280000,
        }


+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {}
        }
        
        
## Loan History [/user/loan-history]

### Loan History [GET]

Header:
APP_SESSION : 21ehwiu1hdiw1rhi1ir13hur3i1ruh1ir

+ Response 200 (application/json)

        {
            "code": "00000",
            "title": "Sukses",
            "message": "Sukses",
            "data": {
                "loanHistory":[
                    {
                        "id":"123546213849451",
                        "kreditLimit":10000000,
                        "purpose":"Pendidikan",
                        "tenor":12,
                        "flatRate":1.69,
                        "effectiveRate":2.95,
                        "provision":600000,
                        "disbursementFee":120000,
                        "insuranceFee":0,
                        "lateInterest":6,
                        "lateFee":200000,
                        "lateTenor":1,
                        "lateTenorUnit":"Month",
                        "receiveFunds":9280000,
                        "requestDate":"2023-03-16 12:20:50",
                        "status":"Waiting Approval",
                        "approvalDate":"",
                        "rejectionDate":"",
                        "rejectionReason":"",
                        "sendEmail":0,
                        "sendSms":0,
                        "isPaid":"",
                        "paidDate":""
                    }
                ]
            }
        }